version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=supersecretkey123456789
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  web:
    build: ./web
    container_name: web_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    stdin_open: true
    tty: true

 