version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5001:5000"
      - "27017:27017"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://localhost:27017/myappdb
      - JWT_SECRET=supersecretkey123456789
    volumes:
      - ./backend:/app
      - /app/node_modules
      - mongo-data:/data/db
    restart: unless-stopped

  web:
    build: ./web
    container_name: web_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    restart: unless-stopped

volumes:
  mongo-data: 