services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5001:5000"
    env_file: .env
    volumes:
      - ./backend:/app
      - /app/node_modules

  web:
    build: ./web
    container_name: web_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api 