# Fikir Proje Bankası - Render Blueprint
# Bu Blueprint, Fikir Proje Bankası uygulamasının altyapısını tanımlar
# Backend entegre veritabanı işlevselliği içerir

services:
  # Backend API Servisi (Entegre Veritabanı ile)
  - type: web
    name: fikir-proje-bankasi-backend
    plan: free
    runtime: node
    repo: https://github.com/tahaayy0/fikir-proje-bankasi.git
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        value: "mongodb+srv://username:password@cluster.mongodb.net/database_name"
        sync: true

  # Frontend Web Servisi
  - type: web
    name: fikir-proje-bankasi-frontend
    plan: free
    runtime: node
    repo: https://github.com/tahaayy0/fikir-proje-bankasi.git
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: fikir-proje-bankasi-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: PORT
        value: 3000
      - key: CI
        value: false 